"""Contract tests for LEG-041 — ParallelAgent (fan-out/fan-in over native beaver).

The parallel composite fans out each branch to the child class's inbox with
``level + 1`` and ``current_index = 0``, keeping the SAME ``task_id`` — the task
id is the task's identity and never changes anywhere in the flow, including
across a fan-out. Each branch carries an **autogenerated ``branch_id``** (distinct
per branch at this level of the same task, constant along the branch's sequence,
preserved through the branch's whole execution) that names its join slot. The
join bookkeeping is keyed directly on the constant ``task_id`` (O(1) fetch; no
child→parent scan). On all-complete it builds its payload from the branch
results (H3 building the payload), decrements ``level`` (−1) and resumes its own level
(Schema 2 §12.4). Nothing waits and nothing is locked: branches run as soon as
their deposit lands on their queue (release parallelism, rule 8).
"""

from __future__ import annotations

import pytest
from beaver import AsyncBeaverDB

from legio.agents.base import AgentBase
from legio.agents.parallel_agent import ParallelAgent
from legio.flow import (
    ExecutionRequestMessage,
    ExecutionResultMessage,
    build_payload,
)
from legio.naming import queue_key


class Branch(AgentBase):
    """An atomic branch: reads its input under ``input_as`` and constructs its
    output under ``output_as``."""

    def __init__(self, *, key: str, input_as: str, output_as: str, **kwargs: object) -> None:
        self._key = key
        self._input_as = input_as
        super().__init__(**kwargs, output_as=output_as)  # type: ignore[call-arg]

    async def _handle(self, request: ExecutionRequestMessage) -> dict:
        inp = request.payload.get(self._input_as, {})
        return build_payload({self._key: inp.get("seed", 0)}, output_as=self._output_as)


async def pop_one(db: AsyncBeaverDB, agent_id: str) -> dict | None:
    try:
        item = await db.queue(queue_key(agent_id)).get(block=False)
    except IndexError:
        return None
    return item.data


def build_parallel(
    *,
    db: AsyncBeaverDB,
    branches,
    agent_id: str = "par",
    input_as: str = "main",
    output_as: str = "par",
) -> ParallelAgent:
    return ParallelAgent(
        agent_id=agent_id, db=db, branches=branches, input_as=input_as, output_as=output_as
    )


def par_request(
    *,
    task_id: str,
    payload: dict,
    route: tuple[tuple[str, str], ...],
    current_index: int,
    end_of_level_queue: str,
    level: int = 1,
) -> ExecutionRequestMessage:
    return ExecutionRequestMessage(
        level_route=route,
        current_index=current_index,
        end_of_level_queue=end_of_level_queue,
        level=level,
        launcher_class=route[0][0] if route else "",
        task_id=task_id,
        payload=payload,
    )


async def fan_out_and_collect(
    *, db: AsyncBeaverDB, par: ParallelAgent, request: ExecutionRequestMessage
) -> list[ExecutionRequestMessage]:
    """Deposit a request on the parallel, run one dispatch, and read back each
    fanned-out child (keeping fan-out order). Returns the child messages."""
    await db.queue(queue_key(par._agent_id)).put(request.model_dump(mode="json"), priority=0.0)
    assert await par.process_next() is True
    children: list[ExecutionRequestMessage] = []
    for branch_class, _ in par._branches:
        item = await pop_one(db, branch_class)
        assert item is not None
        children.append(ExecutionRequestMessage.model_validate(item))
    return children


def child_result(
    *,
    branch_id: str,
    level_route: tuple[tuple[str, str], ...],
    task_id: str,
    payload: dict,
    level: int = 2,
    current_index: int = 0,
) -> ExecutionResultMessage:
    """Build a branch's returning result carrying the parent-assigned branch_id."""
    return ExecutionResultMessage(
        level_route=level_route,
        current_index=current_index,
        end_of_level_queue="par",
        level=level,
        launcher_class="main",
        task_id=task_id,
        branch_id=branch_id,
        payload=payload,
    )


@pytest.mark.asyncio
async def test_parallel_fans_out_both_branches_sharing_task_id(
    beaver_db: AsyncBeaverDB,
) -> None:
    """Both branches get a request (current_index 0, level+1) that keep the task
    id — the task id never changes in the flow (release parallelism). Each branch
    gets an autogenerated branch_id, distinct per branch of the same task."""
    par = build_parallel(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    request = par_request(
        task_id="P-root",
        payload={"main": {"seed": 9}},
        route=(("main", "main"), ("par", "par")),
        current_index=1,
        end_of_level_queue="result:P-root",
    )
    children = await fan_out_and_collect(db=beaver_db, par=par, request=request)
    r1, r2 = children[0], children[1]

    # both branches fanned out: current_index 0, one level deeper
    assert r1.current_index == 0 and r2.current_index == 0
    assert r1.level == 2 and r2.level == 2
    # branches return to the parallel's gathering queue, collapsed onto its inbox
    assert r1.end_of_level_queue == "par"
    assert r2.end_of_level_queue == "par"
    # the task id stays constant across the fan-out — it is the task's identity
    assert r1.task_id == "P-root"
    assert r2.task_id == "P-root"
    # the shared input is re-keyed under each branch's own input_as
    assert r1.payload == {"b1": {"seed": 9}}
    assert r2.payload == {"b2": {"seed": 9}}
    # each branch has an autogenerated, distinct branch_id (the join slot)
    assert r1.branch_id
    assert r2.branch_id
    assert r1.branch_id != r2.branch_id


@pytest.mark.asyncio
async def test_parallel_two_same_class_branches_get_distinct_branch_ids(
    beaver_db: AsyncBeaverDB,
) -> None:
    """Two branches of the very same class/sequence in one task are one task with
    two distinct join slots — their autogenerated branch_ids differ, so they do
    not collide on join (the very case a class-name slot identity would break)."""
    par = build_parallel(db=beaver_db, branches=[("same", "same"), ("same", "same")])
    request = par_request(
        task_id="P-same",
        payload={"main": {"seed": 5}},
        route=(("main", "main"), ("par", "par")),
        current_index=1,
        end_of_level_queue="result:P-same",
    )
    children = await fan_out_and_collect(db=beaver_db, par=par, request=request)
    a, b = children[0], children[1]
    assert a.branch_id != b.branch_id
    # both land on the same child class queue, yet are distinct slots of one task
    assert a.task_id == b.task_id == "P-same"


@pytest.mark.asyncio
async def test_parallel_does_not_advance_until_all_branches_return(
    beaver_db: AsyncBeaverDB,
) -> None:
    """After fan-out the parallel has not advanced; only when ALL branches
    return (joined) does it resume its own level."""
    par = build_parallel(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    request = par_request(
        task_id="P-partial",
        payload={"main": {"seed": 1}},
        route=(("main", "main"), ("par", "par"), ("after", "after")),
        current_index=1,
        end_of_level_queue="result:P-partial",
    )
    children = await fan_out_and_collect(db=beaver_db, par=par, request=request)
    child1, child2 = children[0], children[1]

    # One branch returns; the other has not. The parallel must NOT advance yet.
    await beaver_db.queue(queue_key("par")).put(
        child_result(
            branch_id=child1.branch_id,
            level_route=(("b1", "b1"),),
            task_id="P-partial",
            payload={"b1": 1},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    # process_next dispatches the result; no "after" deposit yet
    assert await par.process_next() is True
    assert await pop_one(beaver_db, "after") is None

    # Second branch returns -> now the join completes and the parallel advances.
    await beaver_db.queue(queue_key("par")).put(
        child_result(
            branch_id=child2.branch_id,
            level_route=(("b2", "b2"),),
            task_id="P-partial",
            payload={"b2": 2},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await par.process_next() is True
    advanced = await pop_one(beaver_db, "after")
    assert advanced is not None
    adv = ExecutionRequestMessage.model_validate(advanced)
    assert adv.current_index == 2
    assert adv.level == 1
    assert adv.task_id == "P-partial"
    assert adv.payload == {"after": {"b1": 1, "b2": 2}}


@pytest.mark.asyncio
async def test_parallel_joins_and_delivers_to_flow_end(
    beaver_db: AsyncBeaverDB,
) -> None:
    """A parallel that is the last step of level 1 delivers the final result to
    the final-result queue on all-complete."""
    par = build_parallel(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    request = par_request(
        task_id="P-end",
        payload={"main": {"seed": 4}},
        route=(("main", "main"), ("par", "par")),
        current_index=1,
        end_of_level_queue="result:P-end",
    )
    children = await fan_out_and_collect(db=beaver_db, par=par, request=request)

    for child, branch_name in ((children[0], "b1"), (children[1], "b2")):
        await beaver_db.queue(queue_key("par")).put(
            child_result(
                branch_id=child.branch_id,
                level_route=((branch_name, branch_name),),
                task_id="P-end",
                payload={branch_name: 4},
            ).model_dump(mode="json"),
            priority=0.0,
        )
    await par.process_next()
    await par.process_next()

    result_item = await pop_one(beaver_db, "result:P-end")
    assert result_item is not None
    result = ExecutionResultMessage.model_validate(result_item)
    assert result.task_id == "P-end"
    assert result.payload == {"par": {"b1": 4, "b2": 4}}


@pytest.mark.asyncio
async def test_parallel_joins_a_multi_step_branch_by_branch_id(
    beaver_db: AsyncBeaverDB,
) -> None:
    """A composite (multi-step) branch returns with an expanded ``level_route``
    whose first element is the branch's first *step*, not the branch class. The
    parallel must still slot it correctly via the preserved autogenerated
    ``branch_id`` the parent assigned at fan-out (LEG-041 branch_id schema field).
    """
    par = build_parallel(db=beaver_db, branches=[("seqbranch", "seqbranch"), ("atomic", "atomic")])
    request = par_request(
        task_id="P-branchy",
        payload={"main": {"seed": 3}},
        route=(("main", "main"), ("par", "par"), ("after", "after")),
        current_index=1,
        end_of_level_queue="result:P-branchy",
    )
    children = await fan_out_and_collect(db=beaver_db, par=par, request=request)
    seq_branch, atomic_branch = children[0], children[1]

    # The multi-step branch ('seqbranch') returns with the expanded level_route
    # (("summ_a", ...), ("summ_b", ...)) but keeps the parent-assigned branch_id.
    await beaver_db.queue(queue_key("par")).put(
        child_result(
            branch_id=seq_branch.branch_id,
            level_route=(("summ_a", "summ_a"), ("summ_b", "summ_b")),
            task_id="P-branchy",
            payload={"seq": "ok"},
            current_index=1,
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await par.process_next() is True

    # Second (atomic) branch still returns with its own branch_id.
    await beaver_db.queue(queue_key("par")).put(
        child_result(
            branch_id=atomic_branch.branch_id,
            level_route=(("atomic", "atomic"),),
            task_id="P-branchy",
            payload={"at": 1},
        ).model_dump(mode="json"),
        priority=0.0,
    )
    assert await par.process_next() is True

    advanced = await pop_one(beaver_db, "after")
    assert advanced is not None
    adv = ExecutionRequestMessage.model_validate(advanced)
    assert adv.current_index == 2
    assert adv.level == 1
    assert adv.task_id == "P-branchy"
    assert adv.payload == {"after": {"seq": "ok", "at": 1}}


@pytest.mark.asyncio
async def test_parallel_resume_preserves_its_own_branch_id(
    beaver_db: AsyncBeaverDB,
) -> None:
    """A parallel nested as a branch of an outer parallel must resume its own
    level carrying the outer-assigned ``branch_id``, so that when it later closes
    to the outer gathering queue the outer fan-in still slots it correctly."""
    par = build_parallel(db=beaver_db, branches=[("b1", "b1"), ("b2", "b2")])
    # Incoming request arrived as a branch of an outer parallel -> branch_id set
    # (autogenerated by the outer parallel).
    request = par_request(
        task_id="P-nested",
        payload={"main": {"seed": 1}},
        route=(("main", "main"), ("par", "par"), ("after", "after")),
        current_index=1,
        end_of_level_queue="result:P-nested",
        level=2,
    )
    outer_branch_id = "P-nested:outer:0"
    await beaver_db.queue(queue_key("par")).put(
        request.model_dump(mode="json") | {"branch_id": outer_branch_id},
        priority=0.0,
    )
    assert await par.process_next() is True
    children = []
    for branch_class, _ in par._branches:
        item = await pop_one(beaver_db, branch_class)
        assert item is not None
        children.append(ExecutionRequestMessage.model_validate(item))

    # Both this inner parallel's branches return with their own autogenerated ids.
    for child, branch_class in zip(children, [c for c, _ in par._branches]):
        await beaver_db.queue(queue_key("par")).put(
            child_result(
                branch_id=child.branch_id,
                level_route=((branch_class, branch_class),),
                task_id="P-nested",
                payload={branch_class: 1},
                level=3,
            ).model_dump(mode="json"),
            priority=0.0,
        )
        assert await par.process_next() is True

    # The resumed advance must carry the outer branch_id, NOT an empty value.
    advanced = await pop_one(beaver_db, "after")
    assert advanced is not None
    adv = ExecutionRequestMessage.model_validate(advanced)
    assert adv.current_index == 2
    assert adv.task_id == "P-nested"
    assert adv.branch_id == outer_branch_id


@pytest.mark.asyncio
async def test_parallel_with_no_branches_fails_visibly(beaver_db: AsyncBeaverDB) -> None:
    """An empty parallel is a construction error, never silent (rule 9)."""
    par = build_parallel(db=beaver_db, branches=[])
    request = par_request(
        task_id="P-empty",
        payload={},
        route=(("par", "par"),),
        current_index=0,
        end_of_level_queue="result:P-empty",
    )
    await beaver_db.queue(queue_key("par")).put(request.model_dump(mode="json"), priority=0.0)

    await par.process_next()

    result_item = await pop_one(beaver_db, "result:P-empty")
    assert result_item is not None
    result = ExecutionResultMessage.model_validate(result_item)
    assert result.task_id == "P-empty"
    assert "error" in result.payload
