"""`legio.agents.composite_agent` — the unified composite runner (LEG-040/LEG-044).

A composite (`type: composite` + `branches`, AGENT_LIFECYCLE §4.10/§4.11) has
**one** runner that handles every arity uniformly: a composite with a single
branch (a sequence) and one with several branches (a parallel) are the same
agent, the same code path.

- **Fan-out** (`execution_request`): for each branch the composite deposits that
  branch's **loader-resolved `level_route`** — its `(class, input_as)` steps —
  with `current_index = 0`, `end_of_level_queue` = this composite's gathering
  queue (collapsed onto its own queue, by message-type dispatch), `level + 1`,
  the SAME `task_id`, and a **fresh autogenerated `branch_id`** (uuid4 — no
  parent-derived naming, distinct from its own and from every other branch
  across all levels, constant along the branch's sequence). It re-keys its
  shared `input_as` under each branch's first step's `input_as` (§12.1). A step
  whose name references a `type: composite` agent stays as a position in the
  branch's route: that composite is invoked like any capability agent through
  its inbox and performs its own fan-out recursively (reuse by reference).
- **Fan-in** (`execution_result`): the result's `branch_id` names the join slot;
  its `task_id` is the join key (direct fetch, no scan). The composite accounts
  for fan-in one result per `branch_id`, conserving it across a multi-step
  branch (whose returned `level_route` expands to its own steps) and across
  failures (an `error` result, rule 9). The join completes when every
  branch_id of the task is present.
- **Build + resume**: on fan-in completion the composite **builds its payload**
  — its declared `output_as` from the branch results — decrements `level` (−1)
  and resumes its own level through the uniform Schema 2 advance, with the
  `end_of_level_queue` its creator supplied.

Nothing waits and nothing is locked (rule 8): branches run as soon as their
deposit lands on their queue; the join is bookkeeping, not polling-blocking.
Errors are never silent (rule 9).
"""

from __future__ import annotations

import logging
import uuid
from collections.abc import Sequence
from typing import Any

from legio.agents.base import AgentBase
from legio.flow import ExecutionRequestMessage, MessageType, build_payload

logger = logging.getLogger(__name__)

# Each composite class keeps its in-flight join continuation here, keyed by the
# TASK id (constant across the flow). Multiple concurrent tasks simply occupy
# several keys.
_STATE_SCOPE = "state:composite"


class CompositeAgent(AgentBase):
    """The unified composite runner: ramify to branches, gather, build."""

    def __init__(
        self,
        *,
        agent_id: str,
        db: Any,
        branches: Sequence[Sequence[tuple[str, str]]],
        input_as: str = "",
        output_as: str = "",
    ) -> None:
        super().__init__(agent_id=agent_id, db=db, output_as=output_as)
        # Each branch is a route of (class, input_as) — the branch's own
        # loader-resolved steps (re-keying info, §12.1).
        self._branches: list[tuple[tuple[str, str], ...]] = [
            tuple(branch) for branch in branches
        ]
        self._input_as = input_as
        self._state = db.dict(f"{_STATE_SCOPE}:{agent_id}")

    async def _handle(self, request: ExecutionRequestMessage) -> dict[str, Any] | None:
        """Dispatch by message type: a request fans out, a result fans in."""
        if request.message_type is MessageType.EXECUTION_RESULT:
            await self._fan_in(request)
            return None
        await self._fan_out(request)
        return None

    async def _fan_out(self, request: ExecutionRequestMessage) -> None:
        """Deposit one request per branch with its own expanded route."""
        if not self._branches:
            raise ValueError(f"composite agent {self._agent_id!r} has no branches")

        existing = await self._state.fetch(request.task_id)
        if existing is not None:
            logger.debug(
                "composite already fanned out agent=%s task=%s",
                self._agent_id,
                request.task_id,
            )
            return

        slots: dict[str, dict[str, Any]] = {}
        for index, branch_route in enumerate(self._branches):
            branch_slot = str(uuid.uuid4())
            first_class, first_input_as = branch_route[0]
            child = ExecutionRequestMessage(
                level_route=branch_route,
                current_index=0,
                end_of_level_queue=self._agent_id,  # this composite's gathering queue
                level=request.level + 1,
                launcher_class=request.launcher_class,
                task_id=request.task_id,
                branch_id=branch_slot,
                payload=(
                    {first_input_as: request.payload[self._input_as]}
                    if self._input_as and self._input_as in request.payload
                    else dict(request.payload)
                ),
            )
            logger.info(
                "composite fan-out agent=%s task=%s branch=%s first=%s steps=%d level=%s branch_id=%s",
                self._agent_id,
                request.task_id,
                index,
                first_class,
                len(branch_route),
                child.level,
                branch_slot,
            )
            await self._deliver(first_class, child.model_dump(mode="json"))
            slots[branch_slot] = {"result": None, "route": branch_route}

        record = {
            "continuation": {
                "level_route": list(request.level_route),
                "current_index": request.current_index,
                "end_of_level_queue": request.end_of_level_queue,
                "level": request.level,
                "launcher_class": request.launcher_class,
                "task_id": request.task_id,
                "branch_id": request.branch_id,
                "payload": dict(request.payload),
            },
            "slots": slots,
        }
        await self._state.set(request.task_id, record)

    async def _fan_in(self, request: ExecutionRequestMessage) -> None:
        """Account for one returned branch; when all are in, build and resume."""
        record = await self._state.fetch(request.task_id)
        if record is None:
            raise ValueError(
                f"composite {self._agent_id!r}: no fan-out for task={request.task_id}"
            )

        branch = request.branch_id or ""
        slot = record["slots"].get(branch)
        if slot is None:
            raise ValueError(
                f"composite {self._agent_id!r}: unknown branch={branch!r} for task={request.task_id}"
            )
        slot["result"] = dict(request.payload)

        if any(s["result"] is None for s in record["slots"].values()):
            logger.debug(
                "composite partial agent=%s task=%s",
                self._agent_id,
                request.task_id,
            )
            await self._state.set(request.task_id, record)
            return

        logger.info("composite joined agent=%s task=%s", self._agent_id, request.task_id)
        result_payload = self._build_branch_payload(record)
        await self._state.delete(request.task_id)
        await self._resume_level(record, result_payload)

    def _build_branch_payload(self, record: dict[str, Any]) -> dict[str, Any]:
        """Build the composite's output from the branch results.

        Each branch produced ``{branch_output_as: value}``; the composite
        gathers them and **constructs its own payload** under its ``output_as``
        (AGENT_LIFECYCLE §12.1/§12.4): no union, no accumulation.
        """
        gathered = {}
        for slot in record["slots"].values():
            gathered.update(dict(slot["result"]))
        return build_payload(gathered, output_as=self._output_as)

    async def _resume_level(
        self, record: dict[str, Any], result_payload: dict[str, Any]
    ) -> None:
        """Resume the composite's own level via the uniform Schema 2 advance."""
        cont = record["continuation"]
        route = tuple((step[0], step[1]) for step in cont["level_route"])
        resume = ExecutionRequestMessage(
            level_route=route,
            current_index=cont["current_index"],
            end_of_level_queue=cont["end_of_level_queue"],
            level=cont["level"],
            launcher_class=cont["launcher_class"],
            task_id=cont["task_id"],
            branch_id=cont["branch_id"],
            payload=result_payload,
        )
        await self._route_outcome(resume, result_payload)


__all__ = ["CompositeAgent"]
